banking_system/urls.py
from django.urls import path

from . import views

app_name = 'banking_system'

urlpatterns = [
    path('', views.index, name='index'),
    path('account/<str:account_id>/', views.account_info, name='account_info'),
    path('new_bank_account/<str:customer_id>/', views.new_bank_account, name='new_bank_account'),
    path('loan/<str:loan_id>/', views.loan_info, name='loan_info'),
    path('payment/<str:loan_id>/', views.payment_request, name='payment_request'),
    path('payment_conf/', views.payment, name='payment'),
    path('transfer/<str:account_id>/', views.transfer_request, name='transfer_request'),
    path('transfer_attempt/', views.transfer, name='transfer'),
    path('transfer_attempt/', views.transfer, name='transfer_attempt'),

    path('transfer_from_bank/', views.transfer_from_bank, name="transfer_from_bank"),

    path('new_loan/<user_id>/', views.new_loan, name='new_loan'),    
    path('loan_request_sent/', views.loan_request_sent, name='loan_request_sent'),
    path('customer_overview/<str:customer_id>/', views.customer_overview, name='customer_overview'),
    path('new_user/', views.new_user, name='new_user'),
    path('new_customer/', views.new_customer, name='new_customer'),
    path('save_new_customer/', views.save_new_customer, name='save_new_customer'),
    path('loan_approval/<str:loan_id>/', views.loan_approval, name='loan_approval'),
    path('add_funds/<str:account_id>/', views.add_funds, name='add_funds'),
    path('add_funds_complete/', views.add_funds_complete, name='add_funds_complete'),
    #rest
    path('get_bankaccount/<str:account_id>/', views.get_bankaccount, name='get_bankaccount'),
]

django_mandatory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('banking_system.urls')),
    path('accounts/', include('login_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
   path('login/', views.login, name='login'),
   path('verify/', views.verify_user, name='verify_user'),
   path('logout/', views.logout, name='logout'),
   path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
   path('password_reset/', views.password_reset, name='password_reset'),
   path('sign_up/', views.sign_up, name='sign_up'),
   path('delete_account/', views.delete_account, name='delete_account'),
]

banking_system/forms.py
from django.forms import ModelForm
from .models import *
from django import forms

class RankForm(ModelForm):
  class Meta:
    model = Customer
    fields = ['rank']
    
class CustomerForm(ModelForm):
  class Meta:
    model = Customer
    exclude = ['user']
    widgets = {
        'dob': forms.DateInput(format=('%m/%d/%Y'), attrs={ 'placeholder':'Select a date', 'type':'date'}),
    }

banking_system/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse
from .models import *
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
import datetime
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.db import transaction
from .forms import *
from .utils import send_sms_loan_approved
from cryptography.fernet import Fernet
import django_rq
import random
import requests
from uuid import uuid4

import threading
from asgiref.sync import async_to_sync, sync_to_async
from multiprocessing.dummy import Pool

from datetime import date
import pytz

import time

#rest

from django.http import JsonResponse
import io
from rest_framework.parsers import JSONParser
from .serializers import BankAccountSerializer
import json

def get_bankaccount(request, account_id):
    """
    List all bank accounts
    """
    if request.method == 'GET':
        bankaccount = BankAccount.objects.get(id=account_id)
        serializer = BankAccountSerializer(bankaccount)
        return JsonResponse(serializer.data, safe=False)

def bankaccount_exists(request):
    return BankAccount.objects.get(id=request.post['accountid']).exists()


#end rest

@login_required
def index(request):

    context = {}
    if Customer.objects.filter(user = request.user.id).exists():
        customer = Customer.objects.get(user = request.user.id)
        context = {
          'customer' : customer
        }
        return render(request, 'banking_system/index.html', context)

    elif BankEmployee.objects.filter(user = request.user.id).exists():
        employee = BankEmployee.objects.get(user = request.user.id)
        customers = Customer.objects.all()
        accounts = BankAccount.objects.all()
        loans = Loan.objects.all()
        for c in customers:
            c.acc_total = BankAccount.objects.filter(customer = c).count()
            c.loan_approved_total = Loan.objects.filter(customer = c, status = 'Approved').count()
            c.loan_pending_total = Loan.objects.filter(customer = c, status = 'Pending').count()

        context = {
          'customers' : customers,
          'accounts' : accounts
        }
        return render(request, 'banking_system/employee_portal.html', context)

    else:
        pass

@login_required
@permission_required('banking_system.view_customer')
def customer_overview(request, customer_id):
    customer = Customer.objects.get(id = customer_id)
    if request.method == "POST":
        form = RankForm(request.POST, instance = customer)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('banking_system:index'))

    form = RankForm(instance=customer)
    employee = True
    context = {
        'customer' : customer,
        'employee' : employee,
        'form' : form
    }
    return render(request, 'banking_system/index.html', context)


@login_required
def account_info(request, account_id):
    account = BankAccount.objects.get(id=account_id)

    context = {
      'account' : account
    }

    return render(request, 'banking_system/account_info.html', context)

@login_required
def loan_info(request, loan_id):
    employee = False
    if BankEmployee.objects.filter(user = request.user.id).exists():
        employee = True
    loan = Loan.objects.get(id=loan_id)
    context = {
      'loan' : loan,
      'employee' : employee
    }
    return render(request, 'banking_system/loan_info.html', context)

#add permission for loan approval
@login_required
def loan_approval(request, loan_id):
    if request.method == "GET":
        #update loan status
        loan = Loan.objects.get(id=loan_id)
        loan.status = 'Approved'
        loan.approver = BankEmployee.objects.get(user = request.user.id) 
        loan.start_date = date.today()
        loan.save()

        #record transfer
        bank_master_acc = BankAccount.objects.get(is_bank=True)
        Ledger.transaction(loan.amount, bank_master_acc.id, loan.recipient_account.id, 'Successful', loan, True)

        django_rq.enqueue(send_sms_loan_approved, {
               'balance' : loan.amount,
               'phone' : loan.customer.phone,
            })

        return HttpResponseRedirect(reverse('banking_system:index'))
    return render(request, 'banking_system/loan_approval')

@login_required
def new_bank_account(request, customer_id):
    if request.method == "GET":
        account = BankAccount()
        account.customer = Customer.objects.get(id=customer_id)
        account.save()
    return HttpResponseRedirect(reverse('banking_system:index'))

@login_required
def payment_request(request, loan_id):
    loan = Loan.objects.get(id=loan_id)
    context = {
      'loan' : loan,
    }
    return render(request, 'banking_system/payment.html', context)

@login_required
@permission_required('banking_system.add_payment')
def payment(request):
    context = {}
    if request.method == "POST":
        loan_id = request.POST["pk"]
        amount = request.POST["amount"]
        account_id = request.POST["accounts"]
        loan = Loan.objects.get(id=loan_id)
        account = BankAccount.objects.get(id=account_id)

        if not amount:
            context.update({
              'error' : 'Please enter an amount for the payment.'
            })
        else:
            amount = float(amount)
            if amount <= 0:
                context.update ({
                  'error' : 'Please enter a valid amount for the payment.'
                })
            elif amount > account.balance:
                context.update ({
                  'error' : "You don't have enough funds for this payment. Please try again."
                })
            elif amount > loan.balance:
                context.update ({
                  'error' : 'The amount is larger than the loan balance.'
                })
            elif amount and amount>0 and amount<=account.balance and amount <= loan.balance: 

                #record payment
                Ledger.transaction(amount, account.id, loan_id, 'Successful', None, False, True, False)

                return HttpResponseRedirect(reverse('banking_system:index'))
            else:
                pass
    else:
        pass

    context.update({
      'loan' : loan,
    })
    return render(request, 'banking_system/payment.html', context)

@login_required
def transfer_request(request, account_id):

    account = BankAccount.objects.get(id=account_id)
    banks = Bank.objects.all()
    context = {
      'account' : account,
      'banks' : banks
    }
    return render(request, 'banking_system/transfer.html', context)

@login_required
@permission_required('banking_system.add_transfer')
def transfer(request):
    context = {}
    if request.method == "POST":
        bank_name = request.POST["banks"]
        bank = Bank.objects.get(name=bank_name)
        account_from_id = request.POST["pk_from"]
        account_from = BankAccount.objects.select_for_update().get(id=account_from_id)
        account_to_id = request.POST["pk_to"]
        amount = request.POST["amount"]
        
        pool = Pool()
        
        if not account_to_id:
            print("no account")
            context.update({
              'error2' : 'Please enter the destination account for the transfer'
            })
            
        if not amount:
            print("no amount")

            context.update({
              'error1' : 'Please enter the amount for the transfer'
            })
        
        else: 
            amount = float(amount)

            if account_from.balance<=amount:
              print("no funds")

              context.update({
                'error1' : 'You do not have enough funds to complete this transfer'
              })

            elif amount > 0 and account_to_id and account_from.balance>=amount:
              print("OK")
              
              # internal transfer
              if bank.isthis:
                print("internal")

                # record transfer
                Ledger.transaction(amount, account_from_id, account_to_id, 'Successful')

                return HttpResponseRedirect(reverse('banking_system:index'))

              # external
              else:
                print("external")

                transfer_id = Ledger.outside_transaction(-amount, account_from_id, account_to_id, 'Pending', None, bank.name)
                transfer = Ledger.objects.get(transaction_id=transfer_id)

                #encrypt
                bank_secret = bank.shared_secret
                fernet = Fernet(bank_secret)
                string = f'{transfer_id}/{amount}/{account_from_id}/{account_to_id}/{transfer.date}'
                encrypted_transfer = fernet.encrypt(bytes(string, 'utf-8'))

                url = bank.ipaddress + "/bank/transfer_from_bank/"
                url_ext = bank.ipaddress + "/bank/get_bankaccount/"+account_to_id
                print("step 0")
                thisBank = Bank.objects.get(isthis=True)
                print(thisBank)
                transfer_obj = {
                  'transfer': encrypted_transfer,
                  'bank' : thisBank.ipaddress,
                  'step' : 1
                }
                print(transfer_obj)
                
                #pollr = pool.apply_async(requests.post, args=(url, transfer_obj))
                #print(pollr.get())
                
                preq = requests.get(url_ext)
                if preq.status_code == 200: 
                  pool.apply_async(requests.post, args=(url, transfer_obj))
                else:
                  banks = Bank.objects.all()
                  context.update({
                    'account' : account_from,
                    'banks' : banks,
                    'error1' : 'account does not exist'
                  })
                  

banking_system/templates/banking_system/account_info.html
{% extends "banking_system/base.html" %}
{% load mathfilters %}

{% block content %}
<hr />
<h2>Account Information</h2>
<p>Account No.: {{account.id}}</p>
<p>Account Balance: ${{account.balance}}</p>

<h2>Transaction History</h2>
<table class="table">
    <thead>
        <tr>
            <th>To/From</th>
            <th>Date</th>
            <th>Type</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        {% for t in account.transactions %}
        {% if t.is_loan == True %}
        <tr>
            <td>From Bank</td>
            <td>{{ t.date}}</td>
            <td>Bank Loan</td>
            <td class="green_text">${{ t.amount }}</td>
        </tr>
        {% elif t.is_payment == True %}
        <tr>
            <td>To Loan: {{ t.destination}} </td>
            <td>{{ t.date}}</td>
            <td>Loan Payment</td>
            <td class="red_text">- ${{ t.amount|abs }}</td>
        </tr>
        {% elif t.is_deposit == True %}
        <tr>
            <td>Deposit </td>
            <td>{{ t.date}}</td>
            <td>Deposit</td>
            <td class="green_text">${{ t.amount }}</td>
        </tr>
        {% elif t.source == 'self' %}
        <tr>
            <td>To Account: {{ t.destination}}</td>
            <td>{{ t.date}}</td>
            <td>Transfer</td>
            <td class="red_text">- ${{ t.amount|abs }}</td>
        </tr>
        {% else %}
        <tr>
            <td>From Account: {{ t.source }}</td>
            <td>{{ t.date}}</td>
            <td>Transfer</td>
            <td class="green_text">${{ t.amount }}</td>
        </tr>
        {% endif %}
        {% endfor %}

    </tbody>

</table>
<a class="btn btn-primary" href="{% url 'banking_system:transfer_request' account.id %}">Make Tranfer</a>
<a class="btn btn-primary" href="{% url 'banking_system:add_funds' account.id %}">Add Funds</a>

<br>
{% endblock %}

banking_system/templates/banking_system/add_funds.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h2>Add Funds</h2>
    <p>Account: {{account.id}}</p>
<form action="{% url 'banking_system:add_funds_complete' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="pk" value="{{account.id}}">
    <input type="number" name="amount" placeholder="Choose amount">
    <button class="btn btn-primary">Submit</button>
</form>
{% if error %}
<p class="red_text"> {{ error }}</p>
{% endif %}
<br>
{% endblock %}

banking_system/templates/banking_system/base.html
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <script src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
   <script type="text/javascript" charset="utf8"
      src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
   <script>
      $(document).ready(function () {
         $('.table').DataTable({
            "order": [[1, "desc"]]
         });
      });


   </script>
   <title>Laura's Bank</title>

   {% load static %}

   <link rel="stylesheet" type="text/css" href="{% static 'banking_system/style.css' %}">
</head>

<body>

   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Bank</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
         aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
               <a class="nav-link" href="{% url 'banking_system:index' %}">Home <span
                     class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
               <a class="nav-link" href="{% url 'login_app:delete_account' %}">Delete Account</a>
            </li>
         </ul>
         <form class="form-inline my-2 my-lg-0">
            <p class="mr-sm-2">Welcome <span id="user_name">{{ user }} </span></p>
         </form>
         <a class="btn btn-sm btn-danger my-2 my-sm-0" href="{% url 'login_app:logout' %}">Log out</a>
      </div>
   </nav>

   {% block content %}
   {% endblock %}
   {% block footer %}
   {% endblock %}
</body>
<script>
   //document.cookie = "username={{user}}";
   var user = document.querySelector('#user_name');
   var socket = new WebSocket('ws://' + window.location.host + '/ws/bank/');
   socket.onmessage = function (e) {
      var data = JSON.parse(e.data);
      if (data.token != document.cookie && data.username == user.innerText) {
         window.location.reload(true);
      }

   }
   socket.onopen = () => socket.send(JSON.stringify({
      'username': user.innerText,
      'token': document.cookie
   }));
</script>

</html>

banking_system/templates/banking_system/employee_portal.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h3>Customers</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Tier</th>
                <th>Active Bank Accounts</th>
                <th>Approved Loans</th>
                <th>Pending Loans</th>
            </tr>
        <thead>
        <tbody>
        {% for c in customers  %}
        <tr>
          <td>
              <a href="{% url 'banking_system:customer_overview' c.id %}">{{ c.name }}</a>
             
          </td>
          <td>{{ c.rank }}</td>
          <td>{{ c.acc_total }}</td>
          <td>{{ c.loan_approved_total }}</td>
          <td>{{ c.loan_pending_total }}</td>
        </tr>

        {% endfor %}
        </tbody>
    </table>
    <form action="{% url 'banking_system:new_user' %}">
        <button class="btn btn-primary">Add Customer</button>
    </form>
    
{% endblock %}

banking_system/templates/banking_system/index.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />

<h3>Account Overview</h3>
<p>Account Owner: {{customer.name}}</p>
<div style="display: inline;">
  <p>
    {% if employee %}
  <form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <button class="btn btn-primary">Save</button>
  </form>

  {%else%}
  Rank: {{customer.rank}}
  {% endif %}
  </p>
</div>



<hr />
<script>

  //rest
//   $(document).ready(function() {
//     $('#bankAccounts').DataTable( {
//         "ajax": {
//                  "processing": true,
//                  "dataSrc": ""
//              },
//         "columns": [
//                      { "data": "id" },
//                      { "data": "balance" }
//                  ]} 
//         );
// } );
</script>
<table class="table" id="bankAccounts">
  <thead>
    <tr>
      <th>Account No</th>
      <th>Balance</th>
    </tr>
    <thead>
    <tbody>
      {% for a in customer.accounts %}
      <tr>
        <td>{{ a.id }} <a class="btn btn-info" href="{% url 'banking_system:account_info' a.id %}">View</a></td>

        <td>${{ a.balance }}</td>

      </tr>
      {% endfor %}
    </tbody>
</table>

<a class="btn btn-primary" href="{% url 'banking_system:new_bank_account' customer.id %}">New Account</a>

<hr />
<table class="table" id="loans">
  <thead>
    <tr>
      <th>Loan ID</th>
      <th>Amount</th>
      <th>Status</th>

    </tr>
  </thead>
  <tbody>
    {% for loan in customer.loans %}
    <tr>
      <td>{{ loan.id }} <a class="btn btn-info" href="{% url 'banking_system:loan_info' loan.id %}">View</a></td>

      <td>${{ loan.amount }}</td>

      {% if loan.status == 'Approved' %}
      <td class="green_text">{{ loan.status }}</td>
      {%else%}
      <td>{{ loan.status }}</td>
      {%endif%}
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if not employee and customer.rank == 'Silver' or not employee and customer.rank == "Gold" %}
<a class="btn btn-primary" href="{% url 'banking_system:new_loan' user.id %}">New Loan</a>
{% endif %}

<hr />
{% endblock %}

banking_system/templates/banking_system/loan_info.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h2>Loan Information</h2>
<p>Customer: {{loan.customer}}</p>
<p>Loan No.: {{loan.id}}</p>
<p>Loan Status: {{loan.status}}</p>
{% if loan.status == 'Approved' %}
<p>Loan Amount: ${{loan.initial_transfer.amount}}</p>
<p>Current Balance Due: ${{loan.balance}}</p>
{% else %}
<p>Requested on: {{ loan.request_date }}</p>
<p>Loan Amount: ${{loan.amount}}</p>
{%endif%}


{%if loan.status == 'Approved'%}
<h2>Payment History</h2>
<table class="table">
  <thead>
    <tr>
      <th>From</th>
      <th>Date</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>From Bank</td>
      <td>{{ loan.initial_transfer.date}}</td>
      <td class="green_text">${{ loan.initial_transfer.amount }}</td>
    </tr>
    {% for p in loan.payments %}
    <tr>
      <td>Account No.: {{ p.source}}</td>
      <td>{{ p.date}}</td>
      <td class="red_text">-${{ p.amount }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% if not employee %}
<form action="{% url 'banking_system:payment_request' loan.id %}">
  <button class="btn btn-primary">Make Payment</button>
</form>
{%endif%}

{%endif%}

{% if loan.status == 'Pending' and employee %}
<form action="{% url 'banking_system:loan_approval' loan.id %}">
  <button class="btn btn-primary">Approve</button>
</form>
{%endif%}

<br>
{% endblock %}

banking_system/templates/banking_system/new_customer.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h3>New Customer</h3>

<form action="{% url 'banking_system:save_new_customer' %}" method="POST">
    {% csrf_token %}

    <h6>Profile Details</h6>
    {{form}}
    <input type="hidden" value={{user.id}} name="user">

    <button class="btn btn-primary">Save</button>
</form>
<hr />
{% if error %}
{{ error }}
{% endif %}

{% endblock %}

banking_system/templates/banking_system/new_loan.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h2>New Loan</h2>
<form action="{% url 'banking_system:loan_request_sent' %}" method="POST">
    {% csrf_token %}
    <select name="accounts" id="accounts">
        <option value="">Choose Recipient Account</option>
        {% for a in customer.accounts %}
        <option value="{{a.id}}">{{a.id}}</option>
        {%endfor%}
    </select>
    <input type="number" name="amount" placeholder="Choose loan amount">
    <input type="number" name="term" placeholder="loan term (months)">
    <button class="btn btn-primary">Apply</button>
</form>
{% if error %}
<p class="red_text"> {{ error }}</p>
{% endif %}
<br>
{% endblock %}

banking_system/templates/banking_system/new_user.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h3>New Customer</h3>

<form action="{% url 'banking_system:new_customer' %}" method="POST">
    {% csrf_token %}
    <h6>Create Login</h6>
    <input type="text" name="user" placeholder="User Name">
    <input type="email" name="email" placeholder="Email Address">
    <input type="password" name="password" placeholder="Password">
    <input type="password" name="confirm_password" placeholder="Confirm Password">
    
    <button class="btn btn-primary">Save</button>
</form>
<hr />
{% if error %}
  <p class="red_text">{{ error }}</p>  
{% endif %}

{% endblock %}

banking_system/templates/banking_system/payment.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h2>Payment</h2>
<p>Loan No.: {{loan.id}}</p>
<p>Loan Balance: ${{loan.balance}}</p>
<form action="{% url 'banking_system:payment' %}" method="POST">
    {% csrf_token %}
    <select name="accounts" id="accounts">
        {% for a in loan.customer.accounts %}
        <option value="{{a.id}}">{{a.id}} - ${{a.balance}}</option>
        {% endfor %}
    </select>
    <input type="hidden" name="pk" value="{{loan.id}}">
    <input type="number" name="amount" placeholder="Payment Amount">
    <button class="btn btn-primary">Pay</button>
</form>

<br>
{% if error %}
<p class="red_text">{{error}}</p>
{% endif %}

{% endblock %}

banking_system/templates/banking_system/transfer.html
{% extends "banking_system/base.html" %}

{% block content %}
<hr />
<h2>Transfer</h2>
<p>Account No.: {{account.id}}</p>
<p>Account Balance: ${{account.balance}}</p>
<form action="{% url 'banking_system:transfer' %}" method="POST">
    {% csrf_token %} 
    <input type="hidden" name="pk_from" value="{{account.id}}">
    <select name="banks" id="banks">
        {% for b in banks %}
            <option value="{{b.name}}">{{b.name}}</option>
        {%endfor%}
    </select>
    <input type="text" name="pk_to" placeholder="Account Number">
    <input type="number" name="amount" placeholder="Transfer Amount">
    <button class="btn btn-primary">Transfer</button>
</form>
{% if error1 %}
    <p class="red_text"> {{ error1 }}</p>     
{% endif %}
{% if error2 %}
    <p class="red_text"> {{ error2 }}</p>     
{% endif %}
<br>
{% endblock %}

banking_system/templates/banking_system/unauthorized.html
You don't have the permissions to access this page. 